### ISSUE TITLE
expandtab, shiftwidth, tabstop should not be hardcoded in!

### ISSUE THREAD

**Issue by redstreet** [davidoc/taskpaper.vim#9]
expandtab, shiftwidth, and tabstop are _user_ preferences! It make no sense for a plugin like taskpaper to hijack them! It only makes sense to set noexpandtab for something like Makefiles where the format inherently demands a tab!

**Comment by davidoc** [comment]
The format does appear to demand a tab, but I'm certainly open to suggestions to make this less intrusive.

**Comment by redstreet** [comment]
I don't see why the format appears to demand a tab. Is there an official definition of the format somewhere? Or are you saying there is another application apart from vim that you use these files with? I use it with spaces (no tabs) within vim, and everything works fine.

**Comment by davidoc** [comment]
Hi,

It's the file format for a Mac application called TaskPaper:

http://www.hogbaysoftware.com/products/taskpaper

Indentation wasn't significant in earlier versions, but more recent versions
require a tab to indent tasks and sub-projects and I was aiming to keep in
line with that.

I don't think there's an official definition of the format other than the
application itself.

It probably makes sense to take out "shiftwidth=4 tabstop=4" from
ftdetect/taskpaper.vim so that users can set their own preferred tabstops.

David

## 

Ánra Taighde - Scoil na hEolaíochta Ríomhaireachta ⁊ na Staitisticí,
 Coláiste na Tríonóide, Baile Átha Cliathi, BÁC 2
Research Fellow - School of Computer Science & Statistics,
 Trinity College Dublin, Dublin 2                    T: +353 1 896 1720

**Comment by redstreet** [comment]
Ah, I see, my bad, I wasn't aware of this. I didn't know people use these files with that app too. I would think there're also people (me, definitely :)) that mainly use these task files with vim. So perhaps we could make the tab settings conditionally dependent on a variable (like g:task_paper_date_format) that one can turn off/on? If you like this, let me know, and I'll submit a change---should be simple.

**Comment by redstreet** [comment]
> It probably makes sense to take out "shiftwidth=4 tabstop=4"

Thanks for removing these!
